/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.ide;


/**
 * Use this class to register ide components.
 */
public class PatientDslIdeModule extends AbstractPatientDslIdeModule {
}
