/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PatientDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/lisa/patientdsl/parser/antlr/internal/InternalPatientDsl.tokens");
	}
}
