/**
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.patientDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Patient</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getInsuranceType <em>Insurance Type</em>}</li>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getInsuranceNumber <em>Insurance Number</em>}</li>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getPhoneNumber <em>Phone Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.lisa.patientdsl.patientDsl.PatientDslPackage#getPatient()
 * @model
 * @generated
 */
public interface Patient extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.lisa.patientdsl.patientDsl.PatientDslPackage#getPatient_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Insurance Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.lisa.patientdsl.patientDsl.InsuranceType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Insurance Type</em>' attribute.
   * @see org.xtext.lisa.patientdsl.patientDsl.InsuranceType
   * @see #setInsuranceType(InsuranceType)
   * @see org.xtext.lisa.patientdsl.patientDsl.PatientDslPackage#getPatient_InsuranceType()
   * @model
   * @generated
   */
  InsuranceType getInsuranceType();

  /**
   * Sets the value of the '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getInsuranceType <em>Insurance Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Insurance Type</em>' attribute.
   * @see org.xtext.lisa.patientdsl.patientDsl.InsuranceType
   * @see #getInsuranceType()
   * @generated
   */
  void setInsuranceType(InsuranceType value);

  /**
   * Returns the value of the '<em><b>Insurance Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Insurance Number</em>' attribute.
   * @see #setInsuranceNumber(int)
   * @see org.xtext.lisa.patientdsl.patientDsl.PatientDslPackage#getPatient_InsuranceNumber()
   * @model
   * @generated
   */
  int getInsuranceNumber();

  /**
   * Sets the value of the '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getInsuranceNumber <em>Insurance Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Insurance Number</em>' attribute.
   * @see #getInsuranceNumber()
   * @generated
   */
  void setInsuranceNumber(int value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.xtext.lisa.patientdsl.patientDsl.PatientDslPackage#getPatient_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Phone Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phone Number</em>' attribute.
   * @see #setPhoneNumber(String)
   * @see org.xtext.lisa.patientdsl.patientDsl.PatientDslPackage#getPatient_PhoneNumber()
   * @model
   * @generated
   */
  String getPhoneNumber();

  /**
   * Sets the value of the '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getPhoneNumber <em>Phone Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phone Number</em>' attribute.
   * @see #getPhoneNumber()
   * @generated
   */
  void setPhoneNumber(String value);

} // Patient
