/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPatientDslScopeProvider extends DelegatingScopeProvider {
}
