/**
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.patientDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.lisa.patientdsl.patientDsl.InsuranceType;
import org.xtext.lisa.patientdsl.patientDsl.Patient;
import org.xtext.lisa.patientdsl.patientDsl.PatientDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Patient</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl#getInsuranceType <em>Insurance Type</em>}</li>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl#getInsuranceNumber <em>Insurance Number</em>}</li>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl#getPhoneNumber <em>Phone Number</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PatientImpl extends MinimalEObjectImpl.Container implements Patient
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getInsuranceType() <em>Insurance Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInsuranceType()
   * @generated
   * @ordered
   */
  protected static final InsuranceType INSURANCE_TYPE_EDEFAULT = InsuranceType.PRIVATE;

  /**
   * The cached value of the '{@link #getInsuranceType() <em>Insurance Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInsuranceType()
   * @generated
   * @ordered
   */
  protected InsuranceType insuranceType = INSURANCE_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getInsuranceNumber() <em>Insurance Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInsuranceNumber()
   * @generated
   * @ordered
   */
  protected static final int INSURANCE_NUMBER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getInsuranceNumber() <em>Insurance Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInsuranceNumber()
   * @generated
   * @ordered
   */
  protected int insuranceNumber = INSURANCE_NUMBER_EDEFAULT;

  /**
   * The default value of the '{@link #getEmail() <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmail()
   * @generated
   * @ordered
   */
  protected static final String EMAIL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEmail() <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmail()
   * @generated
   * @ordered
   */
  protected String email = EMAIL_EDEFAULT;

  /**
   * The default value of the '{@link #getPhoneNumber() <em>Phone Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhoneNumber()
   * @generated
   * @ordered
   */
  protected static final String PHONE_NUMBER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPhoneNumber() <em>Phone Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPhoneNumber()
   * @generated
   * @ordered
   */
  protected String phoneNumber = PHONE_NUMBER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PatientImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PatientDslPackage.Literals.PATIENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PatientDslPackage.PATIENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InsuranceType getInsuranceType()
  {
    return insuranceType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInsuranceType(InsuranceType newInsuranceType)
  {
    InsuranceType oldInsuranceType = insuranceType;
    insuranceType = newInsuranceType == null ? INSURANCE_TYPE_EDEFAULT : newInsuranceType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PatientDslPackage.PATIENT__INSURANCE_TYPE, oldInsuranceType, insuranceType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getInsuranceNumber()
  {
    return insuranceNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInsuranceNumber(int newInsuranceNumber)
  {
    int oldInsuranceNumber = insuranceNumber;
    insuranceNumber = newInsuranceNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PatientDslPackage.PATIENT__INSURANCE_NUMBER, oldInsuranceNumber, insuranceNumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEmail()
  {
    return email;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEmail(String newEmail)
  {
    String oldEmail = email;
    email = newEmail;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PatientDslPackage.PATIENT__EMAIL, oldEmail, email));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPhoneNumber()
  {
    return phoneNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPhoneNumber(String newPhoneNumber)
  {
    String oldPhoneNumber = phoneNumber;
    phoneNumber = newPhoneNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PatientDslPackage.PATIENT__PHONE_NUMBER, oldPhoneNumber, phoneNumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PatientDslPackage.PATIENT__NAME:
        return getName();
      case PatientDslPackage.PATIENT__INSURANCE_TYPE:
        return getInsuranceType();
      case PatientDslPackage.PATIENT__INSURANCE_NUMBER:
        return getInsuranceNumber();
      case PatientDslPackage.PATIENT__EMAIL:
        return getEmail();
      case PatientDslPackage.PATIENT__PHONE_NUMBER:
        return getPhoneNumber();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PatientDslPackage.PATIENT__NAME:
        setName((String)newValue);
        return;
      case PatientDslPackage.PATIENT__INSURANCE_TYPE:
        setInsuranceType((InsuranceType)newValue);
        return;
      case PatientDslPackage.PATIENT__INSURANCE_NUMBER:
        setInsuranceNumber((Integer)newValue);
        return;
      case PatientDslPackage.PATIENT__EMAIL:
        setEmail((String)newValue);
        return;
      case PatientDslPackage.PATIENT__PHONE_NUMBER:
        setPhoneNumber((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PatientDslPackage.PATIENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PatientDslPackage.PATIENT__INSURANCE_TYPE:
        setInsuranceType(INSURANCE_TYPE_EDEFAULT);
        return;
      case PatientDslPackage.PATIENT__INSURANCE_NUMBER:
        setInsuranceNumber(INSURANCE_NUMBER_EDEFAULT);
        return;
      case PatientDslPackage.PATIENT__EMAIL:
        setEmail(EMAIL_EDEFAULT);
        return;
      case PatientDslPackage.PATIENT__PHONE_NUMBER:
        setPhoneNumber(PHONE_NUMBER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PatientDslPackage.PATIENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PatientDslPackage.PATIENT__INSURANCE_TYPE:
        return insuranceType != INSURANCE_TYPE_EDEFAULT;
      case PatientDslPackage.PATIENT__INSURANCE_NUMBER:
        return insuranceNumber != INSURANCE_NUMBER_EDEFAULT;
      case PatientDslPackage.PATIENT__EMAIL:
        return EMAIL_EDEFAULT == null ? email != null : !EMAIL_EDEFAULT.equals(email);
      case PatientDslPackage.PATIENT__PHONE_NUMBER:
        return PHONE_NUMBER_EDEFAULT == null ? phoneNumber != null : !PHONE_NUMBER_EDEFAULT.equals(phoneNumber);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", insuranceType: ");
    result.append(insuranceType);
    result.append(", insuranceNumber: ");
    result.append(insuranceNumber);
    result.append(", email: ");
    result.append(email);
    result.append(", phoneNumber: ");
    result.append(phoneNumber);
    result.append(')');
    return result.toString();
  }

} //PatientImpl
