/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PatientDslUiModule extends AbstractPatientDslUiModule {

	public PatientDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
