/**
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.patientDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.lisa.patientdsl.patientDsl.PatientDslFactory
 * @model kind="package"
 * @generated
 */
public interface PatientDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "patientDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/lisa/patientdsl/PatientDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "patientDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PatientDslPackage eINSTANCE = org.xtext.lisa.patientdsl.patientDsl.impl.PatientDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.lisa.patientdsl.patientDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lisa.patientdsl.patientDsl.impl.ModelImpl
   * @see org.xtext.lisa.patientdsl.patientDsl.impl.PatientDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Patients</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PATIENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl <em>Patient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl
   * @see org.xtext.lisa.patientdsl.patientDsl.impl.PatientDslPackageImpl#getPatient()
   * @generated
   */
  int PATIENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Insurance Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__INSURANCE_TYPE = 1;

  /**
   * The feature id for the '<em><b>Insurance Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__INSURANCE_NUMBER = 2;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__EMAIL = 3;

  /**
   * The feature id for the '<em><b>Phone Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__PHONE_NUMBER = 4;

  /**
   * The number of structural features of the '<em>Patient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.lisa.patientdsl.patientDsl.InsuranceType <em>Insurance Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lisa.patientdsl.patientDsl.InsuranceType
   * @see org.xtext.lisa.patientdsl.patientDsl.impl.PatientDslPackageImpl#getInsuranceType()
   * @generated
   */
  int INSURANCE_TYPE = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.lisa.patientdsl.patientDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.lisa.patientdsl.patientDsl.Model#getPatients <em>Patients</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Patients</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.Model#getPatients()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Patients();

  /**
   * Returns the meta object for class '{@link org.xtext.lisa.patientdsl.patientDsl.Patient <em>Patient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Patient</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.Patient
   * @generated
   */
  EClass getPatient();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.Patient#getName()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getInsuranceType <em>Insurance Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Insurance Type</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.Patient#getInsuranceType()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_InsuranceType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getInsuranceNumber <em>Insurance Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Insurance Number</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.Patient#getInsuranceNumber()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_InsuranceNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.Patient#getEmail()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Email();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lisa.patientdsl.patientDsl.Patient#getPhoneNumber <em>Phone Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phone Number</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.Patient#getPhoneNumber()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_PhoneNumber();

  /**
   * Returns the meta object for enum '{@link org.xtext.lisa.patientdsl.patientDsl.InsuranceType <em>Insurance Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Insurance Type</em>'.
   * @see org.xtext.lisa.patientdsl.patientDsl.InsuranceType
   * @generated
   */
  EEnum getInsuranceType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PatientDslFactory getPatientDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.lisa.patientdsl.patientDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lisa.patientdsl.patientDsl.impl.ModelImpl
     * @see org.xtext.lisa.patientdsl.patientDsl.impl.PatientDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Patients</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PATIENTS = eINSTANCE.getModel_Patients();

    /**
     * The meta object literal for the '{@link org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl <em>Patient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lisa.patientdsl.patientDsl.impl.PatientImpl
     * @see org.xtext.lisa.patientdsl.patientDsl.impl.PatientDslPackageImpl#getPatient()
     * @generated
     */
    EClass PATIENT = eINSTANCE.getPatient();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__NAME = eINSTANCE.getPatient_Name();

    /**
     * The meta object literal for the '<em><b>Insurance Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__INSURANCE_TYPE = eINSTANCE.getPatient_InsuranceType();

    /**
     * The meta object literal for the '<em><b>Insurance Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__INSURANCE_NUMBER = eINSTANCE.getPatient_InsuranceNumber();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__EMAIL = eINSTANCE.getPatient_Email();

    /**
     * The meta object literal for the '<em><b>Phone Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__PHONE_NUMBER = eINSTANCE.getPatient_PhoneNumber();

    /**
     * The meta object literal for the '{@link org.xtext.lisa.patientdsl.patientDsl.InsuranceType <em>Insurance Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lisa.patientdsl.patientDsl.InsuranceType
     * @see org.xtext.lisa.patientdsl.patientDsl.impl.PatientDslPackageImpl#getInsuranceType()
     * @generated
     */
    EEnum INSURANCE_TYPE = eINSTANCE.getInsuranceType();

  }

} //PatientDslPackage
