/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.lisa.patientdsl.ui.internal.PatientdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PatientDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PatientdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PatientdslActivator activator = PatientdslActivator.getInstance();
		return activator != null ? activator.getInjector(PatientdslActivator.ORG_XTEXT_LISA_PATIENTDSL_PATIENTDSL) : null;
	}

}
