/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.lisa.patientdsl.patientDsl.Model;
import org.xtext.lisa.patientdsl.patientDsl.Patient;
import org.xtext.lisa.patientdsl.patientDsl.PatientDslPackage;
import org.xtext.lisa.patientdsl.services.PatientDslGrammarAccess;

@SuppressWarnings("all")
public class PatientDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private PatientDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == PatientDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case PatientDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case PatientDslPackage.PATIENT:
				sequence_Patient(context, (Patient) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     patients+=Patient+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Patient returns Patient
	 *
	 * Constraint:
	 *     (name=ID insuranceType=InsuranceType insuranceNumber=INT email=EMAIL? phoneNumber=STRING?)
	 * </pre>
	 */
	protected void sequence_Patient(ISerializationContext context, Patient semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
