/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.lisa.patientdsl.PatientDslRuntimeModule;
import org.xtext.lisa.patientdsl.PatientDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PatientDslIdeSetup extends PatientDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PatientDslRuntimeModule(), new PatientDslIdeModule()));
	}
	
}
