/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PatientDslStandaloneSetup extends PatientDslStandaloneSetupGenerated {

	public static void doSetup() {
		new PatientDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
