/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.lisa.patientdsl.parser.antlr.internal.InternalPatientDslParser;
import org.xtext.lisa.patientdsl.services.PatientDslGrammarAccess;

public class PatientDslParser extends AbstractAntlrParser {

	@Inject
	private PatientDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPatientDslParser createParser(XtextTokenStream stream) {
		return new InternalPatientDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public PatientDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PatientDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
