/*
 * generated by Xtext 2.33.0
 */
package org.xtext.lisa.patientdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.lisa.patientdsl.ui.internal.PatientdslActivator;

public class PatientDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PatientdslActivator.getInstance().getInjector("org.xtext.lisa.patientdsl.PatientDsl");
	}

}
